// <auto-generated />
namespace IDSS_RouteAndQualityForShippers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedlatlongandaddedposition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedlatlongandaddedposition));
        
        string IMigrationMetadata.Id
        {
            get { return "201705100824394_removed lat long and added position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
