// <auto-generated />
namespace IDSS_RouteAndQualityForShippers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedsuppliesparameters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsuppliesparameters));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121233045_added supplies parameters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
