// <auto-generated />
namespace IDSS_RouteAndQualityForShippers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedrestofparamsforQuality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedrestofparamsforQuality));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121147066_Added rest of params for Quality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
